### ISSUE TITLE
The 1-hour-off bug

### ISSUE THREAD

**Issue by Kaens** [LFriede/x64dbg-updater#1]
After having updated mere moments ago:
![Something like this](https://lithi.io/file/6563.png)
I recall it might have something to do with the way NTFS works. Maybe not, though.

**Comment by LFriede** [comment]
Hi, thanks for reporting. I'll take a look at it.

**Comment by LFriede** [comment]
Hi Kaens, I was able to reproduce this error. It looks like the filetime in the zip archive is not converted to utc at unpacking but ntfs uses utc. So as I played around with timezones the displayed "current file date" and time was everytime exactly the same after updating, regardless of the timezone. But it changes when I changed timezones in windows. So the 1-hour gap changed with timezones after a new update. A quick workaround was to set the file time to the current after unpacking. This is done in the batch file, so please try the latest `_update.bat` I commited, then let the plugin apply an update and it should do what it supposed to. Looks like I didn't notice it because my timezone matches the one of the zip files.

I have a better fix in mind, but I need some time for this. I'll leave this issue open until I've done it, but for now everything should work.

**Comment by LFriede** [comment]
Next version will check against the commit hash instead of the file date, so I think this issue can be closed. Maybe I'll include a widget in the updater dialog which displays the latest commits too.
